from __future__ import annotations

from typing import Any, Dict, List


def _contains_any(text: str, keywords: List[str]) -> bool:
    return any(k in text for k in keywords)


def run_orchestrator(state: Dict[str, Any]) -> Dict[str, Any]:
    source = (state.get("current_code") or state.get("original_code") or "").lower()

    plan: List[str] = []

    security_keywords = [
        "auth", "token", "jwt", "password", "secret", "sql", "select ", "insert ",
        "update ", "delete ", "database", "db.", "cursor", "execute("
    ]
    performance_keywords = [
        "for ", "while ", "range(", ".sort(", "recursion", "append("
    ]

    if _contains_any(source, security_keywords):
        plan.append("security")
    if _contains_any(source, performance_keywords):
        plan.append("performance")

    plan.append("test")
    plan.append("docs")

    seen = set()
    deduped = []
    for step in plan:
        if step not in seen:
            deduped.append(step)
            seen.add(step)

    state["routing_plan"] = deduped
    state["state_summary"] = "Routing plan generated by orchestrator."
    state["retry_count"] = 0
    state["active_agent"] = None
    return state